# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5356ecb6e133f3cd35f03360dfa888b0cd5a62639246ab98e551b659b4e8e2048765bfaa1acf1b19c639a5b23e17f88cf8c6ae3f167a90c22fe320f60229ffc2

test:
  secret_key_base: d95034fbcac3c7ca79009bd73147e0a8889b177a0706105f34a254b6fe34d7845917a88a58a9cef675eb22210b86803629776265879f7bd277c87ea9bd6d3b32

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
